name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  call-shared-build:
    uses: alxch-/reusable-workflows-demo/.github/workflows/build.yml@v1.1.0
    with:
      build-target: production
    secrets:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: echo "Linting code..."
